### ISSUE TITLE
使用 Chatbox 访问 Azure 地址时会报错

### ISSUE THREAD

**Issue by scomper** [haibbo/cf-openai-azure-proxy#1]
使用 [chatbox](https://github.com/Bin-Huang/chatbox/releases) 访问时会有报错。
使用 Opencat 返回正常

Error parsing item: [DONE]
Error Details: SyntaxError: JSON Parse error: Unexpected identifier "DONE"

**Comment by haibbo** [comment]
解决了 DONE的问题, 又遇到了其他问题, 可能是因为Azure OpenAI Service是一段一段回复的, chatbox不太兼容这种方式.

API Request Failed: 
```
Error parsing item: {"id":"chatcmpl-72ipyCgRwzWT4UCpzQS69cqUMTY1g","object".
Error Details: SyntaxError: JSON Parse error: Expected ':' before value in object property definition
```

**Comment by haibbo** [comment]
@scomper 试试看新版本, 实现了打印机模式, chatbox可用了       

原理就是, 从Azure OpenAI Service拿到的消息虽然是一段一段的, 但给客户端的时候我拆出一条条的消息, 依次给.
