### ISSUE TITLE
Uncaught ReferenceError: resourceName is not defined at worker.js:2:20 (Code: 10021)

### ISSUE THREAD

**Issue by 47tse** [haibbo/cf-openai-azure-proxy#14]
将js文件复制到worker里面是，提示“”，无法保存和部署，如下图：
<img width="766" alt="image" src="https://user-images.githubusercontent.com/121725429/232688563-6dd6a9dd-3b47-436e-aa3d-137030886fe9.png">

**Comment by huwan** [comment]
如果你想使用环境变量来传入resourceName 和 deployName的话，先去 Cloudflare worker 控制台添加这两个环境变量和对应的值，再把代码拷贝粘贴过去就能保存部署了。

如果你不想使用环境变量，可以直接修改RESOURCE_NAME和DEPLOY_NAME为实际的值。

**Comment by 47tse** [comment]
感谢，已经解决！
