### ISSUE TITLE
Error for new version

### ISSUE THREAD

**Issue by kotobuki09** [haibbo/cf-openai-azure-proxy#16]
After trying the new mapping version, I got this error: 
[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later
I only config for GPT4 model only and it's seem like it's didn't work as well as previous version in my case

**Comment by haibbo** [comment]
which client did you use? chatgpt-web?

**Comment by kotobuki09** [comment]
I used https://github.com/Chanzhaoyu/chatgpt-web. I didn't set up any environment variable in Cloudflare but I did add some like this for the web https://i.imgur.com/KOc75XN.png

**Comment by haibbo** [comment]
1,  You should set environment variable in Cloudflare like this (with your azure‘s settings ):

![image](https://user-images.githubusercontent.com/1295315/233384224-aa6581f0-26a4-49cf-ae25-4dfb466143da.png)

2, change chatgpt-web‘s OPENAI_API_BASE_URL to your cloudflare worker’s

Refer to README for details.

**Comment by jhhuang96** [comment]
Hi @haibbo, 

I think your project is amazing! I noticed in the Readme that you tested several clients. Could you please recommend which one would be best to use on Windows?

Thank you!

**Comment by haibbo** [comment]
> Hi @haibbo,
> 
> I think your project is amazing! I noticed in the Readme that you tested several clients. Could you please recommend which one would be best to use on Windows?
> 
> Thank you!
You can try chatbox: https://github.com/Bin-Huang/chatbox

**Comment by haibbo** [comment]
> Thanks! I know that but I modify the value directly in the code and didn't use the env variable. Even with the env variable is still how similar issue. While the previous version is working in my case.

Can you show me through images how you config env or code?

**Comment by jhhuang96** [comment]
> > Hi @haibbo,
> > I think your project is amazing! I noticed in the Readme that you tested several clients. Could you please recommend which one would be best to use on Windows?
> > Thank you!
> 
> You can try chatbox: https://github.com/Bin-Huang/chatbox
> 
> I am optimistic about the future development of nofwl(https://github.com/lencx/nofwl). The author will update it soon. However, I do not recommend using the current version which do not support custom API host.

Are you saying that the author will be releasing a new version with support for Azure OpenAI API? If that's the case, it would be fantastic!

**Comment by orange1027** [comment]
![image](https://user-images.githubusercontent.com/120333977/234240248-2d76a1bb-52f0-4df3-9a3a-ec43cbe9c01f.png)
Thank you! I encountered a 404 error in my Cloudflare Worker deployment. What could be the reason?

**Comment by huwan** [comment]
If you are referring to receiving a "404 Not Found" message in the Cloudflare Workers quick editor (dashboard playground), there is no need to worry. This simply means that the code is working correctly. This is the result of the quick editor's previewer accessing the URL directly without providing any required parameters. You can ignore this issue and proceed to test whether the configured proxy interface works properly on a ChatGPT client.

**Comment by orange1027** [comment]
Thank you. Sure enough, it can be used normally

**Comment by orange1027** [comment]
> > > Hi @haibbo,
> > > I think your project is amazing! I noticed in the Readme that you tested several clients. Could you please recommend which one would be best to use on Windows?
> > > Thank you!
> > 
> > 
> > You can try chatbox: https://github.com/Bin-Huang/chatbox
> > I am optimistic about the future development of nofwl(https://github.com/lencx/nofwl). The author will update it soon. However, I do not recommend using the current version which do not support custom API host.
> 
> Are you saying that the author will be releasing a new version with support for Azure OpenAI API? If that's the case, it would be fantastic!
Thanks for your project, can you recommend a good application for Android client？

**Comment by haibbo** [comment]
@orange1027 My friends are using https://play.google.com/store/apps/details?id=com.bytemyth.ama&utm_source=joruan.com&pli=1
