### ISSUE TITLE
ChatGPT-Next-Web v2.0+中打印机模式失效的问题

### ISSUE THREAD

**Issue by huwan** [haibbo/cf-openai-azure-proxy#19]
在Yidadaa/ChatGPT-Next-Web的最新版本[v2.0+](https://github.com/Yidadaa/ChatGPT-Next-Web/releases/tag/v2.0.1)中，使用本项目转换的API，会出现打印机模式失效的情况，输出变为一段一段显示的形式，并且在内容输出完毕后会依然显示“Typing...”，需要等待一小会儿才能结束。尝试切换到OpenAI官方API Key和URL进行测试，输出正常。

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1451009/235033248-b57824e6-3b0a-4221-8bb5-0624c1da5776.png">

**Comment by axelburks** [comment]
在几个 App 中尝试均有该问题，可能是 Azure 修改了输出格式，需要适配下

**Comment by haibbo** [comment]
之前azure 解决了3.5的这些问题, 我就移除了针对这个model的特殊处理. 最近它们又把bug加回来了     汗

试试新版本

**Comment by huwan** [comment]
我使用ChatGPT-Next-Web测试了一下，没有问题，可以正常以打印机模式显示，也可以正常结束。多谢~
