### ISSUE TITLE
可以支持stream吗？

### ISSUE THREAD

**Issue by r-hou** [haibbo/cf-openai-azure-proxy#2]
我尝试使用opencat使用该代理，但是发现不支持stream

**Comment by haibbo** [comment]
其实他是支持stream的, 只是Azure OpenAI service 会积累一段信息再返回.

你在azure试试它的playground, 结果应该和你在opencat上看到的一样

**Comment by haibbo** [comment]
👍 加换行符 让会话STOP   应该可以, 我明天调调看.

**Comment by kotobuki09** [comment]
Besides the issue with the stream answer is not ending through the proxy. I also got the issue that all answers are individual and it's not related even in the same chat session. Is this normal?

**Comment by haibbo** [comment]
Support stream now, please update code and try

**Comment by lzhgus** [comment]
Hi @haibbo, thank you for the update. I tested the latest code and the stream is working now. The printer effect has also been achieved, but there is one problem, the code block is no longer highlighted. Did something go wrong when parsing the data?

**Comment by haibbo** [comment]
> Hi @haibbo, thank you for the update. I tested the latest code and the stream is working now. The printer effect has also been achieved, but there is one problem, the code block is no longer highlighted. Did something go wrong when parsing the data?

which client do you use?

**Comment by kotobuki09** [comment]
> Hi @haibbo, thank you for the update. I tested the latest code and the stream is working now. The printer effect has also been achieved, but there is one problem, the code block is no longer highlighted. Did something go wrong when parsing the data?

The code block is working on my case with [this](https://github.com/Chanzhaoyu/chatgpt-web) client. I think you need to check on the client side.

**Comment by lzhgus** [comment]
I am currently using ChatGPT Next Web and will check the client side code.

**Comment by r-hou** [comment]
> Support stream now, please update code and try

非常感谢，现在在opencat体验良好，送上star
