### ISSUE TITLE
404 NOT FOUND 

### ISSUE THREAD

**Issue by JuneZhao** [haibbo/cf-openai-azure-proxy#20]
如果按照你给的instruc 部署的话，只能得到 
![image](https://user-images.githubusercontent.com/1699200/235138363-31b317cc-c3a8-4006-a520-8b3e5f8a2eed.png)

**Comment by iamalexblue** [comment]
请问怎么解决的

**Comment by JuneZhao** [comment]
> 请问怎么解决的

本身文件没有问题，你需要在各种插件中指明你的API key 以及他给的endpoint 就可以正常访问了
