### ISSUE TITLE
延迟问题

### ISSUE THREAD

**Issue by wangjiatao** [haibbo/cf-openai-azure-proxy#21]
首先，感谢作者开源这个项目。
其次，目前使用的是cluodflare的免费1天10w的worker+opencat+梯子的方案， 在每次提问后，需要等待大概3·5秒才会返回答案。 想请问如果采用付费版本的workder，能降低这个等待的时间么？谢谢。

**Comment by haibbo** [comment]
你好, 这个和 cloudflare 没有关系
这是Azure OpenAI Service 的问题, 你可以用一下它的Playground, 它回复是一段一段的, 我这边把一段一段拆成一个个Token, 依次回客户端 实现了打印机效果.   你说的3s就是第一段出现的时间.
