### ISSUE TITLE
The script error [OpenAI] 服务器拒绝访问，请稍后再试

### ISSUE THREAD

**Issue by kotobuki09** [haibbo/cf-openai-azure-proxy#22]
It's working if I put model gpt 3.5, but I remove model gpt 3.5 it's not working at all. I cannot use mode 4 with this script I believe
And showing this error: [OpenAI] 服务器拒绝访问，请稍后再试
[https://i.imgur.com/Uoj2vOx.png](https://i.imgur.com/Uoj2vOx.png)

**Comment by haibbo** [comment]
which model do you select in your client? in your case without 3.5, you must select gpt-4.

**Comment by kotobuki09** [comment]
I see what you mean! You need to specify it even if it's the only option there! Thanks for your reply
