### ISSUE TITLE
如何关闭 打印机 模式

### ISSUE THREAD

**Issue by williamswang23** [haibbo/cf-openai-azure-proxy#23]
感谢作者提供了打印机模式
有个不情之请。请问如何关闭打印机模式？
如果关闭打印机模式就是类似azure广场那种一段段蹦出来的是么？
谢谢。

**Comment by haibbo** [comment]
用下面的函数 替换stream函数
```js
// Add new line
async function stream(readable, writable) {
  const reader = readable.getReader();
  const writer = writable.getWriter();
  const encoder = new TextEncoder();

  const newline = "\n";
  const encodedNewline = encoder.encode(newline);

  while (true) {
    let { value, done } = await reader.read();
    if (done) {
      break;
    }

    await writer.write(value);
  }
  await writer.write(encodedNewline);
  await writer.close();
}
```
你可以体验下, 更喜欢一段段的输出? 期待反馈

**Comment by wangjiatao** [comment]
感谢您的帮助，我先体验下，后面回来写对比感受。 这个issue我写好对比感受后再关闭。🤝

**Comment by wangjiatao** [comment]
您好，我刚用您提供的函数替换掉了原始的steam函数，然后下面的handlemodel函数及其下面的代码也需要替换么？还是只要替换掉 stream函数即可？ 因为我替换了几分钟，在opencat上感觉和之前类似，还是打字机模式，而不是一段段的蹦出来。

**Comment by luoyujian** [comment]
> 用下面的函数 替换stream函数
> 
> ```js
> // Add new line
> async function stream(readable, writable) {
>   const reader = readable.getReader();
>   const writer = writable.getWriter();
>   const encoder = new TextEncoder();
> 
>   const newline = "\n";
>   const encodedNewline = encoder.encode(newline);
> 
>   while (true) {
>     let { value, done } = await reader.read();
>     if (done) {
>       break;
>     }
> 
>     await writer.write(value);
>   }
>   await writer.write(encodedNewline);
>   await writer.close();
> }
> ```
> 
> 你可以体验下, 更喜欢一段段的输出? 期待反馈

请教一下，最近貌似打字机效果消失了，目前使用您的项目部署到了ChatGPT next web项目上，回复都是一段一段出现的。以及另一个OpenAI Translator最近也是一段一段出现了。但是使用openAI原生API的时候，还是以打字机效果呈现，是不是Azure那边有一些更新？ @haibbo

**Comment by haibbo** [comment]
> 您好，我刚用您提供的函数替换掉了原始的steam函数，然后下面的handlemodel函数及其下面的代码也需要替换么？还是只要替换掉 stream函数即可？ 因为我替换了几分钟，在opencat上感觉和之前类似，还是打字机模式，而不是一段段的蹦出来。

刚刚试了下opencat的行为, 他可能把成段的输出做了打印机效果   

我之前是用chatbot-ui试的, 代码替换后 是一段段的

**Comment by williamswang23** [comment]
> 

OK， 那就是opencat内置了打印机效果，不是这边的原因。 谢谢您。
