### ISSUE TITLE
如何部署到服务器上？

### ISSUE THREAD

**Issue by Axe-l** [haibbo/cf-openai-azure-proxy#24]
有空闲服务器，不懂如何部署，巨佬有空出个教程

**Comment by haibbo** [comment]
如果你不想使用cloudflare worker 而是用自己的服务器, 可以用docker
```sh
docker run -d -p 8787:8787 -t cf-azure-openai-proxy \
--env RESOURCE_NAME=codegpt \
--env DEPLOY_NAME_GPT35=gpt3 \
--env DEPLOY_NAME_GPT4=gpt4 \
haibbo/cf-openai-azure-proxy:latest
```

**Comment by Dreamshe-92** [comment]
> 如果你不想使用cloudflare worker 而是用自己的服务器, 可以用docker
> 
> ```shell
> docker run -d -p 8787:8787 -t cf-azure-openai-proxy \
> --env RESOURCE_NAME=codegpt \
> --env DEPLOY_NAME_GPT35=gpt3 \
> --env DEPLOY_NAME_GPT4=gpt4 \
> haibbo/cf-openai-azure-proxy:latest
> ```

这个可以配置个域名+nginx  本机 443转8787吗？  同时这个部署之后可以怎么验证一下。

**Comment by s-charvin** [comment]
查找不到此库

**Comment by EchoShoot** [comment]
> 

如果我想把 gpt3 与 gpt3-16k 都注册上, 只考虑用 docker 的情况下
DEPLOY_NAME_GPT35 怎么填?
