### ISSUE TITLE
不能使用0301版本

### ISSUE THREAD

**Issue by Tsuizen** [haibbo/cf-openai-azure-proxy#25]
在chatbox切换到0301响应失败，只能使用默认的gpt3.5-turbo，opencat同样的情况

**Comment by jinppppp** [comment]
我也是这样。只能使用gpt3.5-turbo

**Comment by peizh** [comment]
好像今天用突然不行了？配置没动

**Comment by haibbo** [comment]
@Tsuizen @jinppppp 需要增加对应的mapper:
```js
const mapper = {
     'gpt-3.5-turbo': 'gpt3',
     'gpt-4': 'gpt4' 
   };
```
增加gpt-3.5-turbo-0301的映射
```js
const mapper = {
     'gpt-3.5-turbo': 'gpt3',
      'gpt-3.5-turbo-0301': 'gpt3-0301',
     'gpt-4': 'gpt4' 
   };
```
gpt3-0301  改为你azure 这个模型的deploy name

**Comment by haibbo** [comment]
> 好像今天用突然不行了？配置没动

那一部分不行了, 我自己一直在用 未发现问题

**Comment by Tsuizen** [comment]
@haibbo 感谢，已经可以使用了，其实这里映射的就是0301，和客户端选择的模型没有关系吧。

**Comment by peizh** [comment]
> 

看了下，是因为我自己的 Azure OpenAI 被停用了，而且不能重新激活……

**Comment by abrahamgreyson** [comment]
@peizh 你好，请问会因为什么而被封？有告诉你理由吗
