### ISSUE TITLE
How to solve the problem of ' Missing model mapper ' ? Thank you for your answers

### ISSUE THREAD

**Issue by yyzz-zju-2020** [haibbo/cf-openai-azure-proxy#26]
![1](https://user-images.githubusercontent.com/131962319/236662005-4911a698-7826-4dd3-b318-00045a6ae723.png)

**Comment by haibbo** [comment]
parameters like below:

<img width="924" alt="image" src="https://github.com/haibbo/cf-openai-azure-proxy/assets/1295315/f77202cc-fc74-45c8-9b4e-312eae0e791b">

**Comment by Pwolf-Lin** [comment]
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/35656865/db899f9a-41f9-401f-915e-ae0544269a86)
The same question, but it's 404 for my request, I don't know how to solve, thank you for your answers

**Comment by haibbo** [comment]
@Pwolf-Lin Parameters problem, I suggest you use a real ChatGPT client to access your interface.
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/1295315/b9f0c884-126d-406a-ba0f-0212cb26b00c)

**Comment by Pwolf-Lin** [comment]
Thank you for your answer.  Although  it's 404 for the request, it can still use return data though chathub for edge.
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/35656865/dbe9d621-1512-4de6-a4f4-31c9bbd32e1d)

**Comment by ShinChven** [comment]
line 38, give a default model deploy name.

**Comment by Pwolf-Lin** [comment]
404 does not affect your usage. You can try your worker URL and access it on the client side. There should be a return value.

**Comment by Iambihua** [comment]
However, when I added a custom domain to OpenCat, it returned a 403 status code.

**Comment by Pwolf-Lin** [comment]
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/35656865/809e8f66-1ecf-4500-ba33-c978bedc114f)
The same with you, but I can use it in the ChatGPT Next web.

**Comment by Iambihua** [comment]
Can you use it in OpenCat?
