### ISSUE TITLE
返回404

### ISSUE THREAD

**Issue by freetosmash** [haibbo/cf-openai-azure-proxy#29]
您好，抱歉因为我没有技术背景，自己用chatgpt研究了半天，发现大概是path的问题所以返回都是404
但好像我自己也发现不了做错了哪里，请教下
![Xnip2023-05-14_22-26-34](https://github.com/haibbo/cf-openai-azure-proxy/assets/33079010/5bcb2d32-82ab-4b67-9f8e-915896350b73)

**Comment by haibbo** [comment]
你直接用真实的客户端来试

**Comment by haibbo** [comment]
类似这样的配置: 
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/1295315/4a0c478d-1e00-42e8-91a2-97ef6244b1db)

**Comment by myfree88** [comment]
Hi @haibbo :Thanks for your shared:
 1. I config it and  want test as above , where is the authorization token ?
 2. I test it in openCat, and it show Validate success, but when I use it , it show  openAI unexpected http code 403

![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/36387531/ce425939-d958-486b-94f1-54a284eb7167)
![47800067b6be4fcd7e93efa50b2aee3](https://github.com/haibbo/cf-openai-azure-proxy/assets/36387531/44ba6ea0-4fad-454e-be0b-001056022da2)
![684f4d94482a87e0e9f90a00b281560](https://github.com/haibbo/cf-openai-azure-proxy/assets/36387531/a841397d-fe62-4fd0-86a7-5a6aa3112460)

**Comment by IncredibleAaron** [comment]
Authaurization 应该填什么
