### ISSUE TITLE
"必须绑定自定义域名"

### ISSUE THREAD

**Issue by 520xiaopohai** [haibbo/cf-openai-azure-proxy#3]
这里详细的过程作者能贴一下么 对于cloudflare还是不熟悉

**Comment by juanchenjojo** [comment]
铜球~~

**Comment by haibbo** [comment]
如果你可以科学上网, 其实是不需要绑定自定义域名的, 因为cloudflare worker本身就会提供一个 xxx.xxx.wroker.dev的域名.

如:
![image](https://user-images.githubusercontent.com/1295315/230409299-72bc3d09-1bd4-4c2b-baa5-676553e17521.png)


如果你无法科学上网就需要绑定自定义域名,点击上图中的 Add Custom Domains:
输入一个二级域名,  对应的域名要绑定到cloudflare上.
https://developers.cloudflare.com/workers/platform/triggers/custom-domains/
