### ISSUE TITLE
docker run命令和https访问

### ISSUE THREAD

**Issue by qingju32** [haibbo/cf-openai-azure-proxy#38]
docker run -d -p 8787:8787 -t \\
--name cf-azure-openai-proxy \\
--env RESOURCE_NAME=codegpt \\
--env DEPLOY_NAME_GPT35=gpt3 \\
--env DEPLOY_NAME_GPT4=gpt4 \\
haibbo/cf-openai-azure-proxy:latest
好像指定容器名要加--name，不加它就识别成镜像名，然后没有这个镜像

我本地运行好像也可以

怎么实现https访问啊？想部署到服务器上（不然就闲置了）

**Comment by ShinChven** [comment]
在服务器上用 certbot + nginx 部署证书就能实现 https 访问了。

https://atlassc.net/2020/11/09/install-certbot

**Comment by qingju32** [comment]
实现了，用了Nginx容器部署了腾讯云申请的SSL证书。两个容器内存占用400M左右，然后好像速度和deno部署的差不多。
