### ISSUE TITLE
Azure官方文档建议把API 版本迁移到 GA "2023-05-15"

### ISSUE THREAD

**Issue by Caixiaopig** [haibbo/cf-openai-azure-proxy#39]
官方文档来源: https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/whats-new#azure-openai-chat-completion-general-availability-ga

需修改的代码: https://github.com/haibbo/cf-openai-azure-proxy/blob/b851be3c110356197c6e86b1c452df244a8496df/cf-openai-azure-proxy.js#LL10C4-L10C4

**Comment by Caixiaopig** [comment]
提了一个PR

**Comment by haibbo** [comment]
Finished: https://github.com/haibbo/cf-openai-azure-proxy/pull/40
