### ISSUE TITLE
在cloudflare新建worker后，系统报错，代码 (Code: 10021)

### ISSUE THREAD

**Issue by devin2013** [haibbo/cf-openai-azure-proxy#43]
以下两个参数均已替换
Your Azure OpenAI Resource Name
Your GPT-3.5 model deployment name

在保存并配置后，会显示
Uncaught ReferenceError: *** is not defined at worker.js:2:20 (Code: 10021)

提交GPT4后，它会重写一段新的，但最后还是无法运行。

**Comment by devin2013** [comment]
不好意思，已经解决了 。

**Comment by ShinChven** [comment]
我猜是引号的问题。
