### ISSUE TITLE
求救，怎么都不行。使用opencat弹出Unexpected http code 403

### ISSUE THREAD

**Issue by Graypango** [haibbo/cf-openai-azure-proxy#49]
各种尝试，都不行。我用第一种方式和第二种方式都进行了尝试
// The name of your Azure OpenAI Resource.
const resourceName='RESOURCE_NAME'

// The deployment name you chose when you deployed the model.
const mapper = {
    'gpt-3.5-turbo': 'DEPLOY_NAME_GPT35',
    //'gpt-4': DEPLOY_NAME_GPT4
};

const apiVersion="2023-05-15"

Azure模型名称 gpt-35-turbo
Azure模型版本 0613

Azure的设置如上，是不是版本问题？

**Comment by granken** [comment]
我也是这个报错信息

**Comment by haibbo** [comment]
> const mapper = {
> 'gpt-3.5-turbo': 'DEPLOY_NAME_GPT35',
> //'gpt-4': DEPLOY_NAME_GPT4
> };

你的 部署的名字是 gpt-35-turbo? 是名字,不是model  如果是这样,你应该这么配置:
const mapper = {
'gpt-3.5-turbo': 'gpt-35-turbo',
//'gpt-4': DEPLOY_NAME_GPT4
};


![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/1295315/af3e6302-67dd-455c-867a-cd17b40c2c8c)
