### ISSUE TITLE
Convert User-Set Variables to Environment Variables for Cloudflare Workers

### ISSUE THREAD

**Issue by huwan** [haibbo/cf-openai-azure-proxy#5]
Currently, there are some variables for user settings in `cf-openai-azure-proxy.js`. It would be more convenient to change these variables to environment variables so that users can directly fill in the information in the Cloudflare workers settings. This will make it easier to update the code by simply replacing the entire code instead of having to fill out the variables every time.

https://github.com/haibbo/cf-openai-azure-proxy/blob/3279039f89fe1564c0f86721924e635ee342f89f/cf-openai-azure-proxy.js#L2-L7

I noticed that there is an example of using cloudflare workers' environment variables in [this repo](https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/dist/index.js), which can be referred to. Thank you.

**Comment by haibbo** [comment]
I'm thinking whether to do this or not because it requires users to manipulate environment variables, and I'm concerned that it would add complexity that regular users may not be able to handle.

**Comment by huwan** [comment]
Perhaps we can offer users the flexibility to modify the code directly or set environment variables in the Cloudflare workers settings panel. In case no environment variable is specified, it will default to the values defined in the code. This approach enables users to make direct modifications while also having an alternative option of using environment variables if they so choose.
