### ISSUE TITLE
按照示例改的代码，报错Missing model mapper？想问下如何解决

### ISSUE THREAD

**Issue by itcodes** [haibbo/cf-openai-azure-proxy#51]
![1581690892755_ pic](https://github.com/haibbo/cf-openai-azure-proxy/assets/8282645/ee8c2f84-8908-4d76-94eb-c54172960d0d)
大家有遇到这个问题吗？

**Comment by Cuauhtemoc9** [comment]
+1

**Comment by ShinChven** [comment]
https://atlassc.net/2023/05/30/convert-azure-openai-service-api-to-openai-service-api

```js
const deployName = mapper[modelName] || 'Your model deployment name'; // set a default model deployment name here to avoid possible errors.
```

改这一句

**Comment by Cuauhtemoc9** [comment]
感谢大佬，但不清楚为什么现在变成404了
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/44720250/63619aab-a052-4820-b393-74deadf78b75)

**Comment by Cuauhtemoc9** [comment]
不知道是不是和版本有关系，之前一直用的3.5都没问题，现在加了turbo和0613版本就不行了
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/44720250/ff56a182-e46b-495d-ad99-be6cebde8f83)

**Comment by ShinChven** [comment]
这个情况好像没见过，检查一下模型部署名称

**Comment by ShinChven** [comment]
> 不知道是不是和版本有关系，之前一直用的3.5都没问题，现在加了turbo和0613版本就不行了 ![image](https://user-images.githubusercontent.com/44720250/258704033-ff56a182-e46b-495d-ad99-be6cebde8f83.png) ![image](https://user-images.githubusercontent.com/44720250/258705101-4983a407-501f-4ad8-84ee-0f1efe4ceab3.png)

你们怎么都申请到GPT-4了，我申请4个月了，就是不给。

**Comment by ShinChven** [comment]
```javascript
const apiVersion="2023-05-15";
```

测了一下，改版本号吧。

**Comment by Cuauhtemoc9** [comment]
可以了感谢大佬！！方便的话可以看下telegram~

**Comment by lil-i321** [comment]
> ```js
> const apiVersion="2023-05-15";
> ```
> 
> 测了一下，改版本号吧。 这个版本号是API的版本号，不是模型的版本号。

是不是应该改成这里的版本号？
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/57334649/a8d6ee2c-4170-4167-a106-7412a2e99d13)

**Comment by ShinChven** [comment]
应该是的，别忘记了删掉preview

**Comment by think2011** [comment]
<img width="617" alt="image" src="https://github.com/haibbo/cf-openai-azure-proxy/assets/3961388/617d675b-7144-44ca-946e-f73037ff8669">


有遇到  vscode 的插件 genie Ai 似乎有 bug，传的 model 不对导致出错
