### ISSUE TITLE
求助，为什么不支持上下文啊

### ISSUE THREAD

**Issue by robinhan10211021** [haibbo/cf-openai-azure-proxy#57]
在chatbox和glarity这样的网站和插件中都支持连续对话。但使用cf生成的链接不支持上下文对话。

**Comment by undefinedcodezhong** [comment]
实际上api没有支不支持上下文对话的说法，如果想要有上下文对话的效果，就在给api的messages参数里填充历史对话，就是token消耗的多一点。

**Comment by ShinChven** [comment]
I suggest you monitor this project's network to see how you should send history messages:

https://github.com/Yidadaa/ChatGPT-Next-Web
