### ISSUE TITLE
输出结果中显示乱码

### ISSUE THREAD

**Issue by huwan** [haibbo/cf-openai-azure-proxy#6]
部署了最新的代码，输出结果中有机会产生乱码。尝试了几个客户端，都有这种现象，切换为标准的OpenAI API显示正常。

ChatGPT Next Web 客户端（（上半部分是这个项目的转换的Azure接口，下半部分是OpenAI接口）：
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/1451009/230714561-7e20c695-0e9d-4db3-92b0-5484fd8b577f.png">

另外一个客户端AMA（转换的Azure接口）：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1451009/230714577-155667d7-4a8d-4aa4-8003-532c6d85bc7f.PNG">

**Comment by haibbo** [comment]
应该是今天 打印机模式引进来的， revert掉这个commit就可以了，后面我看看

顺便问下 你喜欢打印机模式 还是azure 原生的？一段一段输出

**Comment by huwan** [comment]
> 应该是今天 打印机模式引进来的， revert掉这个commit就可以了，后面我看看
> 
> 顺便问下 你喜欢打印机模式 还是azure 原生的？一段一段输出

谢谢回复~我个人比较倾向于用打印机模式，跟用OpenAI 官方API体验一致比较好。

**Comment by hbsgithub** [comment]
> https://github.com/Yidadaa/ChatGPT-Next-Web/issues/507#issuecomment-1500971442

参考这个，我将
``buffer += decoder.decode(value);``
修改为
``buffer += decoder.decode(value, { stream: true });``
不知能否解决这一问题？

**Comment by haibbo** [comment]
@huwan 使用了 @hbsgithub 的方案, 应该没有乱码了, 试试看

**Comment by huwan** [comment]
感谢各位~
