### ISSUE TITLE
求更新增加dall-e-3

### ISSUE THREAD

**Issue by CXK3023** [haibbo/cf-openai-azure-proxy#63]
求更新增加dall-e-3，DALL-E 和 GPT-3 或 GPT-4 都是由 OpenAI 开发的，但是它们有点不同。

**Comment by mmwong1984** [comment]
+1

**Comment by ShinChven** [comment]
https://github.com/songquanpeng/one-api/pull/775

**Comment by haibbo** [comment]
已经支持 dall-e-3 @CXK3023 @mmwong1984 
用 chatbox 测试通过:
<img width="1015" alt="image" src="https://github.com/haibbo/cf-openai-azure-proxy/assets/1295315/e9d8f686-7d4a-4523-8b1a-2880e5ae4934">

@ShinChven Thanks
