### ISSUE TITLE
配置opencat后，返回404

### ISSUE THREAD

**Issue by yijia2413** [haibbo/cf-openai-azure-proxy#7]
绑定了域名，并且也能validate success。

请问是什么问题呢？ 不过好像没地方需要填 azure openai的秘钥？

**Comment by yinm0591** [comment]
在填写openai key的地方填入azure openai的秘钥

**Comment by yijia2413** [comment]
如图所示…还是不行，很奇怪。 CF的配置按照你这边的README改了

![image](https://user-images.githubusercontent.com/5038318/230770854-df4f92ee-2a42-4b63-a7a2-662deab5ac9a.png)
![image](https://user-images.githubusercontent.com/5038318/230770868-7231f603-b785-44e9-927d-b523203ea9d2.jpeg)

**Comment by haibbo** [comment]
填好Azure OpenAI Service的key后, 就可以了  不用点API KEY下面的校验

**Comment by yijia2413** [comment]
搞定了，谢谢！
