### ISSUE TITLE
Azure 通过 cloudflare 转openai之后 ，回答内容的末尾总会带一个null

### ISSUE THREAD

**Issue by ConnorCHN** [haibbo/cf-openai-azure-proxy#75]
![image](https://github.com/haibbo/cf-openai-azure-proxy/assets/8830361/66c4c732-2a3c-4b58-a557-81f468517715)
如图所示。不知道什么原因。与软件没有关系，换了好几个都有这个问题

**Comment by ShinChven** [comment]
这个null好像是结束语

**Comment by ConnorCHN** [comment]
我让GPT帮我分析了问题。根据GPT生成的建议修改了，最终还是没有解决生成内容末尾有“null”的问题

![ray-so-export](https://github.com/haibbo/cf-openai-azure-proxy/assets/8830361/9b8db048-a558-43db-b5eb-978374ff0f0a)

**Comment by ConnorCHN** [comment]
问题已解决，不是脚本的问题，是chatbox的问题。
